steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: ${_EXPERIMENT}
  args: [ 
    'build', 
    '-t', 
    'gcr.io/$PROJECT_ID/$REPO_NAME/${_EXPERIMENT}:$COMMIT_SHA',
    '-t', 
    'gcr.io/$PROJECT_ID/$REPO_NAME/${_EXPERIMENT}:$BRANCH_NAME', 
    '.' 
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/$REPO_NAME/${_EXPERIMENT}:$COMMIT_SHA'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/$REPO_NAME/${_EXPERIMENT}:$BRANCH_NAME'
  ]
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    ssh-keyscan github.com >> /root/.ssh/known_hosts
    chmod 644 /root/.ssh/known_hosts
    git config --global user.email "michael@letalone.ca"
    git config --global user.name "Michael Markieta"
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'gcr.io/cloud-builders/git'
  dir: /root
  args: [
    'clone',
    '--verbose',
    'git@github.com:LetAlone-Inc/letalone-deploy.git'
  ]
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'letalone-deploy'
    path: /root/letalone-deploy
- name: 'bash'
  dir: /root
  args: [
    'ls',
    '-al'
  ]
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'letalone-deploy'
    path: /root/letalone-deploy
- name: 'bash'
  dir: /root/letalone-deploy
  args:
  - '-c'
  - |
    sed "s#__IMAGE__#${_IMAGE}#g; s#__PROJECT__#${_ENV_GCP_PROJECT}#g" ${_ENV_GKE_CLUSTER}/${_EXPERIMENT}/templates/deployment.yaml > ${_ENV_GKE_CLUSTER}/${_EXPERIMENT}/deployment.yaml
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'letalone-deploy'
    path: /root/letalone-deploy
- name: 'bash'
  dir: /root/letalone-deploy
  args: [
    'cat',
    '${_ENV_GKE_CLUSTER}/${_EXPERIMENT}/deployment.yaml'
  ]
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'letalone-deploy'
    path: /root/letalone-deploy
- name: 'gcr.io/cloud-builders/git'
  dir: /root/letalone-deploy
  args: [
    'add',
    '.'
  ]
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'letalone-deploy'
    path: /root/letalone-deploy
- name: 'gcr.io/cloud-builders/git'
  dir: /root/letalone-deploy
  args: [
    'commit',
    '-am',
    'update ${_ENV_GKE_CLUSTER}/${_EXPERIMENT}/deployment.yaml'
  ]
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'letalone-deploy'
    path: /root/letalone-deploy
- name: 'gcr.io/cloud-builders/git'
  dir: /root/letalone-deploy
  args: [
    'push',
    'origin',
    'main'
  ]
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'letalone-deploy'
    path: /root/letalone-deploy
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/id_github/versions/latest
    env: 'SSH_KEY'
substitutions:
  _IMAGE: gcr.io/${PROJECT_ID}/${REPO_NAME}/${_EXPERIMENT}:${COMMIT_SHA}
images: [
  'gcr.io/$PROJECT_ID/$REPO_NAME/${_EXPERIMENT}:$COMMIT_SHA',
  'gcr.io/$PROJECT_ID/$REPO_NAME/${_EXPERIMENT}:$BRANCH_NAME'
]